# Site settings
locale: ko
lang: ko-KR
timezone: Asia/Seoul
title: "터진채리의 개발Blog"
description: blog
baseurl: ""
url: "https://chech2.github.io/"

# User settings
username: Lee chaelim
user_description: 굴렁굴렁 굴렁쇠 깍고 깎아 잘 굴러가는 그날까지
user_title: Back-End Developer
email: chaelim3396@gmail.com
instagram_username: chelee._.cherry
linkedin_username: 이채림
github_username: chech2

# Outputting
permalink: /:categories/:title/
paginate: 15                                    # Defaults : 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#facebook_username: mauricio.urraco
# twitter_username: lorem_ipsum
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

toc: true
exclude: ["package.json", "src", "node_modules", "vendor"]
